"""users table

Revision ID: 0c2ada2b076b
Revises: de5a548fff18
Create Date: 2019-05-06 15:59:29.528381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c2ada2b076b'
down_revision = 'de5a548fff18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.create_foreign_key(None, 'post', 'user', ['user_id'], ['id'])
    op.drop_column('post', 'user_nim')
    op.add_column('user', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_column('user', 'nim')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('nim', sa.INTEGER(), nullable=False))
    op.drop_column('user', 'id')
    op.add_column('post', sa.Column('user_nim', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.create_foreign_key(None, 'post', 'user', ['user_nim'], ['nim'])
    op.drop_column('post', 'user_id')
    # ### end Alembic commands ###
